<?php
/**
* @file
* Loads visualizations from Tableau Public with a simple url
*/

/**
 * Implements hook_field_info().
 */
function tableau_public_field_info() {
  return array(
    'tableau_public_info' => array(
      'label' => t('Tableau Visualization'),
      'description' => t("Basic information about a Tableau viz"),
      'settings' => array('max_length' => 255),
      'default_widget' => 'tableau_public_info',
      'default_formatter' => 'tableau_public_info', // This doesn't *have* to be the same name as default_widget's value, this is only coincidence
    ),
    'tableau_public_sheets' => array(
      'label' => t('Tableau Sheets'),
      'description' => t("Create a list of individual sheets within a Tableau viz"),
      'default_widget' => 'tableau_public_sheets',
      'default_formatter' => 'tableau_public_sheets',
    ),
  );
}

/**
 * Implements hook_field_widget_info().
 */
function tableau_public_field_widget_info() {
  return array(
    'tableau_public_sheets' => array(
      'label' => 'Tableau Sheets',
      'field types' => array('tableau_public_sheets'),
      'multiple values' => TRUE,
    ),
    'tableau_public_info' => array(
      'label' => 'Tableau Viz information',
      'field types' => array('tableau_public_info'),
      'multiple values' => FALSE,
    ),
  );
}

/**
 * Implements hook__form_field_ui_field_edit_form_alter().
 *
 * Sets the sheets field to default to unlimited
 */
function tableau_public_form_field_ui_field_edit_form_alter(&$form, &$form_state) {
  if ($form['#field']['type'] == 'tableau_public_sheets') {
    // Hide the cardinality setting on the field settings for properties fields.
    $form['field']['cardinality']['#default_value'] = FIELD_CARDINALITY_UNLIMITED;
  }
}

/**
 * Implements HOOK_FIELD_WIDGET_FORM().
 */
function tableau_public_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  switch ($instance['widget']['type']) {
    case 'tableau_public_sheets':
      // Custom definition for sheet name text field
      $value = isset($items[$delta]['name']) ? $items[$delta]['name'] : '';
      $element['name'] = array(
        '#attributes'     => array(
          'class'         => array('edit-sheet'),
          'title'         => '',
          'rel'           => '',
        ),
        '#type'           => 'textfield',
        '#size'           => 60,
        '#maxlength'      => 255,
        '#title'          => 'Sheet name',
        '#default_value'  => $value,
        '#attached'       => array(),
        '#prefix'         => '<div>',
        '#suffix'         => '</div>'
      );

      // Custom definition for mobile layout boolean checkbox
      $value = isset($items[$delta]['mobile']) ? $items[$delta]['mobile'] : '';
      $element['mobile'] = array(
        '#type'             => 'checkbox',
        '#default_value'    => $value,
        '#on_value'         => 'yes',
        '#off_value'        => 'no',
        '#title'            => 'Mobile layout',
        '#value_key'        => 'mobile',
      );

      break;
    case 'tableau_public_info':
      // Custom definition for viz name text field
      $value = isset($items[$delta]['title']) ? $items[$delta]['title'] : '';
      $element['title'] = array(
        '#attributes'     => array(
          'class'         => array('edit-title'),
          'title'         => '',
          'rel'           => '',
        ),
        '#type'           => 'textfield',
        '#size'           => 60,
        '#maxlength'      => 255,
        '#title'          => 'Viz title',
        '#default_value'  => $value,
        '#attached'       => array(),
        '#prefix'         => '<div>',
        '#suffix'         => '</div>'
      );

      // Custom definition for dynamic title boolean checkbox
      $value = isset($items[$delta]['dynamic']) ? $items[$delta]['dynamic'] : '';
      $element['dynamic'] = array(
        '#type'             => 'checkbox',
        '#default_value'    => $value,
        '#on_value'         => 'yes',
        '#off_value'        => 'no',
        '#title'            => 'Dynamic title',
        '#value_key'        => 'dynamic',
      );

      // Custom definition for short code text field
      $value = isset($items[$delta]['short']) ? $items[$delta]['short'] : '';
      $element['short'] = array(
        '#attributes'     => array(
          'class'         => array('edit-short'),
          'title'         => '',
          'rel'           => '',
        ),
        '#type'           => 'textfield',
        '#size'           => 60,
        '#maxlength'      => 255,
        '#title'          => 'Short code',
        '#default_value'  => $value,
        '#attached'       => array(),
        '#prefix'         => '<div>',
        '#suffix'         => '</div>'
      );

      // Custom definition for short code text field
      $value = isset($items[$delta]['viz']) ? $items[$delta]['viz'] : 'http://';
      $element['viz'] = array(
        '#attributes'     => array(
          'class'         => array('edit-viz'),
          'title'         => '',
          'rel'           => '',
        ),
        '#type'           => 'textfield',
        '#size'           => 60,
        '#maxlength'      => 255,
        '#title'          => 'Viz url',
        '#default_value'  => $value,
        '#attached'       => array(),
        '#prefix'         => '<div>',
        '#suffix'         => '</div>'
      );

      break;
  }

  return $element;
}

/**
 * Implements hook_field_is_empty().
 */
function tableau_public_field_is_empty($item, $field) {
  $temp = array_keys($field['columns']);
  $key = array_shift($temp);
  return empty($item[$key]);
}

/**
 * Implements hook_field_field_formatter_info().
 */
function tableau_public_field_field_formatter_info() {
  return array(
    'tableau_public_info' => array(
      'label' => t('Tableau Visualization'),
      'field types' => array('tableau_public_info'),
    ),
    'tableau_public_sheets' => array(
      'label' => t('Tableau Sheets'),
      'field types' => array('tableau_public_sheets'),
    ),
  );
}

/**
 * Implements hook_field_field_formatter_view().
 */
function tableau_public_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  switch ($display['type']) {
    case 'tableau_public_info':
      $headers = array(
        t('Title'),
        t('Dynamic Title'),
        t('Short Code'),
        t('Vizualization URL'),
      );

      $element[0]['#theme'] = 'table';
      $element[0]['#data'] = array('header' => $headers, 'rows' => $items);
      break;

    case 'tableau_public_sheets':
      $headers = array(
        t('Name'),
        t('Mobile layout'),
      );

      $element[0]['#theme'] = 'table';
      $element[0]['#data'] = array('header' => $headers, 'rows' => $items);
      break;
  }
  return $element;
}

/**
 * Implements hook_field_prepare_view().
 *
 * When you load a field, check to see if it's a Tableau field.
 * If it is, then automatically load the javascripts and
 * populate jQuery.extend().
 */
function tableau_public_field_prepare_view($entity_type, $entities, $field, $instances, $langcode, &$items) {
  if ($field['type'] == 'tableau_public_info') {
    tableau_public_add_viz($items);
  } elseif ($field['type'] == 'tableau_public_sheets') {
    tableau_public_add_sheets($items);
  }
}

/**
 * Grabs viz data from node fields; adds to Drupal.setting js object.
 *
 * @param int $nid
 *   Integer that refers to a node ID.  Function will automatically pull the
 *   correct fields from the node using the nid.
 */
function tableau_public_add_viz($items) {
  // Load javascript files now
  drupal_add_js('https://public.tableau.com/javascripts/api/tableau-2.min.js', array('type' => 'external', 'scope' => 'footer'));
  drupal_add_js(drupal_get_path('module', 'tableau_public') . '/tableau-interactive.js', array('type' => 'file', 'scope' => 'footer'));

  // check to see if any data has already been captured
  $tableau_data = array();
  $javascript = drupal_add_js();
  if ($javascript['settings']['tableau_data']) {
    array_push($tableau_data, $javascript['settings']['tableau_data']);
  }

  // there should only be one tableau viz, but iterate just in case
  $key = key($items);
  foreach ($items[$key] as $item) {
    // Interactive title
    $title = $item['title'];
    // Unique identifier to create a placeholder div for Tableau
    $shorty = $item['short'];
    // Boolean variable to determine whether this Tableau interactive should
    // have a dynamic title
    $dynamic = $item['dynamic'];
    // We have a single Tableau viz url, with an array of individual sheets.
    // Add this to the array of Tableau data
    $tableau_viz = $item['viz'];

    $result = array(
      'title'         => $title,
      'id'            => $shorty,
      'url'           => $tableau_viz,
      'dynamic_title' => $dynamic,
    );
    array_push($tableau_data, $result);
  }

  // Finally, push the tableau_data array to jQuery.extend(Drupal.settings)
  drupal_add_js(array('tableau_data' => $tableau_data), 'setting');
}

/**
 * Grabs sheet data from node fields; adds to Drupal.setting js object.
 * @TODO: refactor
 *
 * @param int $nid
 *   Integer that refers to a node ID.  Function will automatically pull the
 *   correct fields from the node using the nid.
 */
function tableau_public_add_sheets($items) {
  dsm($items, "you can't say I don't give a sheet");
  // check to see if any data has already been captured
  $sheets = array();
  $javascript = drupal_add_js();
  if ($javascript['settings']['tableau_sheets']) {
    array_push($sheets, $javascript['settings']['tableau_sheets']);
  }

  // individual Tableau sheets are stored as a field collection within a
  // field collection.  Go through each sheet individually.
  $key = key($items);
  foreach ($items[$key] as $item) {
//    $sheet_id = $sheet_reference['value'];
//    $sheet = entity_load('field_collection_item',
//      array($sheet_id));
    array_push($sheets, array(
      'name'   => $sheet[$sheet_id]->field_sheet_url['und'][0]['safe_value'],
      'phone_layout' => $sheet[$sheet_id]->field_phone_layout['und'][0]['value']
    ));
  }

  // Finally, push the tableau_data array to jQuery.extend(Drupal.settings)
  drupal_add_js(array('tableau_sheets' => $sheets), 'setting');
}
